framework:
  mailer:
    dsn: '%env(MAILER_DSN)%'
    envelope:
      sender: '%env(MAILER_ENVELOPE_SENDER)%'
      recipients:
        - '%env(MAILER_ENVELOPE_RECIPIENT)%'
    headers:
      From: '%env(MAILER_HEADER_FROM)%'
