services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT:-8083}:80
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/var/www

  php-fpm-queue:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www
    environment:
      CONTAINER_ROLE: queue

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-54322}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailer:
    platform: linux/amd64
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8082:8025"

volumes:
  pgdata: