version: '3.8'

services:
  nginx:
    image: ${REGISTRY}/weather-app-nginx:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    image: ${REGISTRY}/weather-app-php-fpm:${IMAGE_TAG}
    restart: always
    depends_on:
      - postgres

  php-fpm-queue:
    image: ${REGISTRY}/weather-app-php-fpm:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    environment:
      CONTAINER_ROLE: queue

  php-fpm-schedule:
    image: ${REGISTRY}/weather-app-php-fpm:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    environment:
      CONTAINER_ROLE: scheduler

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailer:
    platform: linux/amd64
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8082:8025"

volumes:
  pgdata: